# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/services/exchange/exchange.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='app/services/exchange/exchange.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n$app/services/exchange/exchange.proto\"P\n\x0f\x45xchangeRequest\x12\x14\n\x0cout_currency\x18\x01 \x02(\t\x12\x13\n\x0bin_currency\x18\x02 \x02(\t\x12\x12\n\nout_amount\x18\x03 \x02(\x01\"\"\n\x10\x45xchangeResponse\x12\x0e\n\x06result\x18\x01 \x02(\t2B\n\x08\x45xchange\x12\x36\n\x0fsimple_exchange\x12\x10.ExchangeRequest\x1a\x11.ExchangeResponse'
)




_EXCHANGEREQUEST = _descriptor.Descriptor(
  name='ExchangeRequest',
  full_name='ExchangeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='out_currency', full_name='ExchangeRequest.out_currency', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='in_currency', full_name='ExchangeRequest.in_currency', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='out_amount', full_name='ExchangeRequest.out_amount', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=120,
)


_EXCHANGERESPONSE = _descriptor.Descriptor(
  name='ExchangeResponse',
  full_name='ExchangeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='ExchangeResponse.result', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=122,
  serialized_end=156,
)

DESCRIPTOR.message_types_by_name['ExchangeRequest'] = _EXCHANGEREQUEST
DESCRIPTOR.message_types_by_name['ExchangeResponse'] = _EXCHANGERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ExchangeRequest = _reflection.GeneratedProtocolMessageType('ExchangeRequest', (_message.Message,), {
  'DESCRIPTOR' : _EXCHANGEREQUEST,
  '__module__' : 'app.services.exchange.exchange_pb2'
  # @@protoc_insertion_point(class_scope:ExchangeRequest)
  })
_sym_db.RegisterMessage(ExchangeRequest)

ExchangeResponse = _reflection.GeneratedProtocolMessageType('ExchangeResponse', (_message.Message,), {
  'DESCRIPTOR' : _EXCHANGERESPONSE,
  '__module__' : 'app.services.exchange.exchange_pb2'
  # @@protoc_insertion_point(class_scope:ExchangeResponse)
  })
_sym_db.RegisterMessage(ExchangeResponse)



_EXCHANGE = _descriptor.ServiceDescriptor(
  name='Exchange',
  full_name='Exchange',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=158,
  serialized_end=224,
  methods=[
  _descriptor.MethodDescriptor(
    name='simple_exchange',
    full_name='Exchange.simple_exchange',
    index=0,
    containing_service=None,
    input_type=_EXCHANGEREQUEST,
    output_type=_EXCHANGERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_EXCHANGE)

DESCRIPTOR.services_by_name['Exchange'] = _EXCHANGE

# @@protoc_insertion_point(module_scope)
