# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/services/send_money/send_money.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='app/services/send_money/send_money.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n(app/services/send_money/send_money.proto\"E\n\x10SendMoneyRequest\x12\x10\n\x08\x63urrency\x18\x01 \x02(\t\x12\x0f\n\x07\x61\x63\x63ount\x18\x02 \x02(\t\x12\x0e\n\x06\x61mount\x18\x03 \x02(\x01\"\"\n\x10WithdrawResponse\x12\x0e\n\x06result\x18\x01 \x02(\t\"\x1e\n\x0cSentResponse\x12\x0e\n\x06result\x18\x01 \x02(\t2g\n\tSendMoney\x12\x30\n\x08withdraw\x12\x11.SendMoneyRequest\x1a\x11.WithdrawResponse\x12(\n\x04sent\x12\x11.SendMoneyRequest\x1a\r.SentResponse'
)




_SENDMONEYREQUEST = _descriptor.Descriptor(
  name='SendMoneyRequest',
  full_name='SendMoneyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='currency', full_name='SendMoneyRequest.currency', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='account', full_name='SendMoneyRequest.account', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='amount', full_name='SendMoneyRequest.amount', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=113,
)


_WITHDRAWRESPONSE = _descriptor.Descriptor(
  name='WithdrawResponse',
  full_name='WithdrawResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='WithdrawResponse.result', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=149,
)


_SENTRESPONSE = _descriptor.Descriptor(
  name='SentResponse',
  full_name='SentResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='SentResponse.result', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=151,
  serialized_end=181,
)

DESCRIPTOR.message_types_by_name['SendMoneyRequest'] = _SENDMONEYREQUEST
DESCRIPTOR.message_types_by_name['WithdrawResponse'] = _WITHDRAWRESPONSE
DESCRIPTOR.message_types_by_name['SentResponse'] = _SENTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SendMoneyRequest = _reflection.GeneratedProtocolMessageType('SendMoneyRequest', (_message.Message,), {
  'DESCRIPTOR' : _SENDMONEYREQUEST,
  '__module__' : 'app.services.send_money.send_money_pb2'
  # @@protoc_insertion_point(class_scope:SendMoneyRequest)
  })
_sym_db.RegisterMessage(SendMoneyRequest)

WithdrawResponse = _reflection.GeneratedProtocolMessageType('WithdrawResponse', (_message.Message,), {
  'DESCRIPTOR' : _WITHDRAWRESPONSE,
  '__module__' : 'app.services.send_money.send_money_pb2'
  # @@protoc_insertion_point(class_scope:WithdrawResponse)
  })
_sym_db.RegisterMessage(WithdrawResponse)

SentResponse = _reflection.GeneratedProtocolMessageType('SentResponse', (_message.Message,), {
  'DESCRIPTOR' : _SENTRESPONSE,
  '__module__' : 'app.services.send_money.send_money_pb2'
  # @@protoc_insertion_point(class_scope:SentResponse)
  })
_sym_db.RegisterMessage(SentResponse)



_SENDMONEY = _descriptor.ServiceDescriptor(
  name='SendMoney',
  full_name='SendMoney',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=183,
  serialized_end=286,
  methods=[
  _descriptor.MethodDescriptor(
    name='withdraw',
    full_name='SendMoney.withdraw',
    index=0,
    containing_service=None,
    input_type=_SENDMONEYREQUEST,
    output_type=_WITHDRAWRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='sent',
    full_name='SendMoney.sent',
    index=1,
    containing_service=None,
    input_type=_SENDMONEYREQUEST,
    output_type=_SENTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SENDMONEY)

DESCRIPTOR.services_by_name['SendMoney'] = _SENDMONEY

# @@protoc_insertion_point(module_scope)
